#!/usr/bin/env bash
set -euo pipefail

cd "$(dirname "$0")/.."

npm ci

# When Cursor environment secrets are configured, materialize .env for Next.js/Playwright.
if [[ ! -f .env ]] && [[ -n "${NEXT_PUBLIC_SUPABASE_URL:-}" ]]; then
  cat > .env <<EOF
NEXT_PUBLIC_SUPABASE_URL=${NEXT_PUBLIC_SUPABASE_URL}
NEXT_PUBLIC_SUPABASE_ANON_KEY=${NEXT_PUBLIC_SUPABASE_ANON_KEY:-}
SUPABASE_SERVICE_ROLE_KEY=${SUPABASE_SERVICE_ROLE_KEY:-}
NEXT_PUBLIC_APP_URL=${NEXT_PUBLIC_APP_URL:-http://localhost:3000}
NEXT_PUBLIC_DEFAULT_LOCALE=${NEXT_PUBLIC_DEFAULT_LOCALE:-fr}
METALS_API_URL=${METALS_API_URL:-https://api.metals.dev/v1/latest}
METALS_API_KEY=${METALS_API_KEY:-}
PLAYWRIGHT_BASE_URL=${PLAYWRIGHT_BASE_URL:-http://localhost:3000}
E2E_FIXTURE_PASSWORD=${E2E_FIXTURE_PASSWORD:-}
E2E_BUYER_EMAIL=${E2E_BUYER_EMAIL:-}
E2E_BUYER_PASSWORD=${E2E_BUYER_PASSWORD:-}
E2E_SELLER_EMAIL=${E2E_SELLER_EMAIL:-}
E2E_SELLER_PASSWORD=${E2E_SELLER_PASSWORD:-}
E2E_COOP_APPROVED_EMAIL=${E2E_COOP_APPROVED_EMAIL:-}
E2E_COOP_APPROVED_PASSWORD=${E2E_COOP_APPROVED_PASSWORD:-}
E2E_COOP_PENDING_EMAIL=${E2E_COOP_PENDING_EMAIL:-}
E2E_COOP_PENDING_PASSWORD=${E2E_COOP_PENDING_PASSWORD:-}
E2E_ADMIN_EMAIL=${E2E_ADMIN_EMAIL:-}
E2E_ADMIN_PASSWORD=${E2E_ADMIN_PASSWORD:-}
ADMIN_GATE_SECRET=${ADMIN_GATE_SECRET:-}
ADMIN_PASSPHRASE=${ADMIN_PASSPHRASE:-}
EOF
  echo "[cloud-agent-install] Wrote .env from environment secrets."
fi
