/**
 * One-time build-time generator for DRC province SVG paths.
 * Run: npm run map:generate
 *
 * Input:  scripts/data/drc-provinces.geojson (geoBoundaries COD ADM1, CC BY 4.0)
 * Output: lib/constants/drc-province-paths.ts
 */

import * as fs from 'fs';
import * as path from 'path';
import { geoCentroid, geoMercator, geoPath } from 'd3-geo';
import type { Feature, FeatureCollection, Geometry } from 'geojson';
import { DRC_PROVINCES, type DrcProvince } from '../lib/constants/provinces';

const VIEWBOX_WIDTH = 400;
const VIEWBOX_HEIGHT = 600;

const GEOJSON_PATH = path.join(__dirname, 'data', 'drc-provinces.geojson');
const OUTPUT_PATH = path.join(__dirname, '..', 'lib', 'constants', 'drc-province-paths.ts');

/**
 * Explicit mapping from geoBoundaries ADM1 shapeName to marketplace DRC_PROVINCES values.
 * No fuzzy matching — every shapeName must be listed here.
 */
export const GEOBOUNDARIES_SHAPE_NAME_TO_PROVINCE: Record<string, DrcProvince> = {
  'Lower Uele': 'Bas-Uélé',
  'Upper Uele': 'Haut-Uélé',
  'Central Kasai': 'Kasaï-Central',
  Kasai: 'Kasaï',
  'Kasai-Oriental': 'Kasaï-Oriental',
  'North Kivu': 'Nord-Kivu',
  'South Kivu': 'Sud-Kivu',
  Équateur: 'Équateur',
  'Haut-Katanga': 'Haut-Katanga',
  'Haut-Lomami': 'Haut-Lomami',
  Ituri: 'Ituri',
  Kinshasa: 'Kinshasa',
  'Kongo-Central': 'Kongo-Central',
  Kwango: 'Kwango',
  Kwilu: 'Kwilu',
  Lomami: 'Lomami',
  Lualaba: 'Lualaba',
  'Mai-Ndombe': 'Mai-Ndombe',
  Maniema: 'Maniema',
  Mongala: 'Mongala',
  'Nord-Ubangi': 'Nord-Ubangi',
  Sankuru: 'Sankuru',
  'Sud-Ubangi': 'Sud-Ubangi',
  Tanganyika: 'Tanganyika',
  Tshopo: 'Tshopo',
  Tshuapa: 'Tshuapa',
};

interface ProvincePathEntry {
  province: DrcProvince;
  shapeName: string;
  path: string;
  labelX: number;
  labelY: number;
}

function round(value: number, digits = 2): number {
  const factor = 10 ** digits;
  return Math.round(value * factor) / factor;
}

function rewindFeature(feature: Feature): Feature {
  const cloned = JSON.parse(JSON.stringify(feature)) as Feature;

  if (cloned.geometry.type === 'Polygon') {
    cloned.geometry.coordinates = cloned.geometry.coordinates.map((ring) => [...ring].reverse());
  } else if (cloned.geometry.type === 'MultiPolygon') {
    cloned.geometry.coordinates = cloned.geometry.coordinates.map((polygon) =>
      polygon.map((ring) => [...ring].reverse()),
    );
  }

  return cloned;
}

function main() {
  const raw = fs.readFileSync(GEOJSON_PATH, 'utf8');
  const geojson = JSON.parse(raw) as FeatureCollection<Geometry, { shapeName: string }>;
  const rewoundGeojson: FeatureCollection = {
    type: 'FeatureCollection',
    features: geojson.features.map((feature) => rewindFeature(feature as Feature)),
  };

  const projection = geoMercator().fitSize([VIEWBOX_WIDTH, VIEWBOX_HEIGHT], rewoundGeojson);
  const pathGenerator = geoPath(projection);

  const entries: ProvincePathEntry[] = [];
  const unmapped: string[] = [];
  const mappedProvinces = new Set<DrcProvince>();

  for (const feature of rewoundGeojson.features) {
    const shapeName = (feature.properties as { shapeName: string }).shapeName;
    const province = GEOBOUNDARIES_SHAPE_NAME_TO_PROVINCE[shapeName];

    if (!province) {
      unmapped.push(shapeName);
      continue;
    }

    const projectedFeature = feature;
    const svgPath = pathGenerator(projectedFeature);
    if (!svgPath) {
      throw new Error(`Failed to generate SVG path for ${shapeName}`);
    }

    const [labelX, labelY] = projection(geoCentroid(projectedFeature)) ?? [0, 0];

    entries.push({
      province,
      shapeName,
      path: svgPath,
      labelX: round(labelX),
      labelY: round(labelY),
    });
    mappedProvinces.add(province);
  }

  if (unmapped.length > 0) {
    throw new Error(`Unmapped geoBoundaries shapeNames: ${unmapped.join(', ')}`);
  }

  const missingProvinces = DRC_PROVINCES.filter((province) => !mappedProvinces.has(province));
  if (missingProvinces.length > 0) {
    throw new Error(`DRC_PROVINCES not covered by GeoJSON: ${missingProvinces.join(', ')}`);
  }

  entries.sort((a, b) => a.province.localeCompare(b.province, 'fr'));

  const mappingLines = Object.entries(GEOBOUNDARIES_SHAPE_NAME_TO_PROVINCE)
    .sort(([a], [b]) => a.localeCompare(b))
    .map(([shapeName, province]) => `  '${shapeName}': '${province}',`)
    .join('\n');

  const entryLines = entries
    .map(
      (entry) =>
        `  {\n    province: '${entry.province}',\n    shapeName: '${entry.shapeName}',\n    path: '${entry.path}',\n    labelX: ${entry.labelX},\n    labelY: ${entry.labelY},\n  },`,
    )
    .join('\n');

  const output = `// Generated by scripts/generate-drc-map-paths.ts — do not edit manually.
// Source: geoBoundaries COD ADM1 (CC BY 4.0) — scripts/data/drc-provinces.geojson

import type { DrcProvince } from '@/lib/constants/provinces';

/**
 * Explicit mapping from geoBoundaries ADM1 shapeName to marketplace DRC_PROVINCES values.
 */
export const GEOBOUNDARIES_SHAPE_NAME_TO_PROVINCE = {
${mappingLines}
} as const satisfies Record<string, DrcProvince>;

export interface DrcProvincePathData {
  province: DrcProvince;
  /** Original geoBoundaries shapeName. */
  shapeName: string;
  /** SVG path \`d\` attribute in viewBox coordinates. */
  path: string;
  /** Projected centroid X for tooltip anchoring. */
  labelX: number;
  /** Projected centroid Y for tooltip anchoring. */
  labelY: number;
}

export const DRC_PROVINCE_PATHS: DrcProvincePathData[] = [
${entryLines}
];

export const DRC_MAP_VIEWBOX = '0 0 ${VIEWBOX_WIDTH} ${VIEWBOX_HEIGHT}';
`;

  fs.writeFileSync(OUTPUT_PATH, output, 'utf8');
  console.log(`Wrote ${entries.length} province paths to ${OUTPUT_PATH}`);
}

main();
